### ISSUE TITLE
Python 3 compatible ? 

### ISSUE THREAD

**Issue by xo28122000** [sightmachine/simplecv-examples#12]
I am using python 3 to use this tool and the library file has some python 2 references. Is simplecv compatible with python 3 ? 

**Error code:**

Traceback (most recent call last):

  File "IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-3-78f57c89a189>", line 1, in <module>
    import SimpleCV

  File "anaconda3/lib/python3.7/site-packages/SimpleCV/__init__.py", line 3, in <module>
    from SimpleCV.base import *

  File "anaconda3/lib/python3.7/site-packages/SimpleCV/base.py", line 175
    print 'unit test'
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('unit test')?

**Comment by oostendo** [comment]
No, it's Python 2 only
